#### Code written by: Xinyue Li

In [1]:
import numpy as np

In [2]:
#definition of function for calculating coordinates
def coordinates(i,D,T,O):  #input number of atoms i,distance vector D,theta vector T,omega vector O
    A = np.zeros((i,3))    #create empty matrix to store coordinates
    
    #calculate the 1st atom and store in A
    C1 = np.dot(B1,ei)     
    A[0,0]=C1[0,0]
    A[0,1]=C1[1,0]
    A[0,2]=C1[2,0]
    if i == 1:
        return A
    
    #calculate the first two atoms and store in A
    mid = np.dot(B1,B2)    
    C2 = np.dot(mid,ei)
    A[1,0]=C2[0,0]
    A[1,1]=C2[1,0]
    A[1,2]=C2[2,0]
    if i == 2:
        return A
    
    #calculate the first three atoms and store in A
    mid = np.dot(mid,B3)   
    C3 = np.dot(mid,ei)
    A[2,0]=C3[0,0]
    A[2,1]=C3[1,0]
    A[2,2]=C3[2,0]
    if i == 3:
        return A
    
    #calculate the first i atoms and store in A
    if i>= 4:                          
        for n in range(4,i+1,1):
            #Matrix for the ith atom
            Bi = np.array([[-np.cos(T[n-1]),-np.sin(T[n-1]),0,-D[n-1]*np.cos(T[n-1])],
               [np.sin(T[n-1])*np.cos(O[n-1]),-np.cos(T[n-1])*np.cos(O[n-1]),-np.sin(O[n-1])*D[n-1],np.sin(T[n-1])*np.cos(O[n-1])],
               [np.sin(T[n-1])*np.sin(O[n-1]),-np.cos(T[n-1])*np.sin(O[n-1]),np.cos(O[n-1])*D[n-1],np.sin(T[n-1])*np.sin(O[n-1])],
               [0,0,0,1]])
            #Calculating the Coordinates for the ith atom
            mid = np.dot(mid,Bi)
            Ci = np.dot(mid,ei)  
            A[n-1,0]=Ci[0,0]
            A[n-1,1]=Ci[1,0]
            A[n-1,2]=Ci[2,0]
        return A

In [3]:
# start to use

In [4]:
# Enter distance and angle vectors for all atoms
dist = np.array([0,1,2,3,4,3])
theta = np.array([0,0,30,30,30,30])
omega = np.array([0,0,0,60,60,30])

In [5]:
#transformation matrix
ei = np.array([[0],[0],[0],[1]])

In [6]:
#first transformation matrix
B1 = np.array([[1,0,0,0],[0,1,0,0],[0,0,1,0],[0,0,0,1]])

In [7]:
#second transfromation matrix
B2 = np.array([[-1,0,0,dist[1]],[0,1,0,0],[0,0,-1,0],[0,0,0,1]])
print('B2 =\n',B2)

B2 =
 [[-1  0  0  1]
 [ 0  1  0  0]
 [ 0  0 -1  0]
 [ 0  0  0  1]]


In [8]:
#third transformation matrix
B3 = np.array([[-np.cos(theta[2]),-np.sin(theta[2]),0,-dist[2]*np.cos(theta[2])],
              [np.cos(theta[2]),-np.cos(theta[2]),0,dist[2]*np.sin(theta[2])],
              [0,0,1,0],[0,0,0,1]])
print('B3 =\n',B3)

B3 =
 [[-0.15425145  0.98803162  0.         -0.3085029 ]
 [ 0.15425145 -0.15425145  0.         -1.97606325]
 [ 0.          0.          1.          0.        ]
 [ 0.          0.          0.          1.        ]]


In [11]:
# try out 
#print (coordinates(3,dist,theta,omega))
#print (coordinates(4,dist,theta,omega))
print (coordinates(5,dist,theta,omega))
print (coordinates(6,dist,theta,omega))

[[ 0.          0.          0.        ]
 [ 1.          0.          0.        ]
 [ 1.3085029  -1.97606325  0.        ]
 [ 0.30737064 -2.19259657 -0.30116253]
 [ 0.63044169 -2.00874444  0.7009057 ]]
[[  0.           0.           0.        ]
 [  1.           0.           0.        ]
 [  1.3085029   -1.97606325   0.        ]
 [  0.30737064  -2.19259657  -0.30116253]
 [  0.63044169  -2.00874444   0.7009057 ]
 [  4.20373947  -1.35509787 -10.35443947]]
